<a href="https://colab.research.google.com/github/sakthivelj/DL-pytorch-MedImg/blob/main/DL_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [2]:
# Create Numpy array
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [6]:
#transform to numpy array

np.array(mylist)

array([1, 2, 3])

In [9]:
array = np.array(mylist)
type(array)

numpy.ndarray

In [11]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
type(mylist)

list

In [14]:
# Convert to array
array = np.array(mylist)
type(array)

numpy.ndarray

In [17]:
array.shape

(3, 3)

In [18]:
# Create numpy array

In [22]:
np.arange(0,11,3).shape

(4,)

In [29]:
np.zeros((10,2,3)) + 5

array([[[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.]]])

In [25]:
type(0.)

float

In [37]:
np.linspace(0,10, 18)

array([ 0.        ,  0.58823529,  1.17647059,  1.76470588,  2.35294118,
        2.94117647,  3.52941176,  4.11764706,  4.70588235,  5.29411765,
        5.88235294,  6.47058824,  7.05882353,  7.64705882,  8.23529412,
        8.82352941,  9.41176471, 10.        ])

In [41]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [51]:
np.random.rand(4,4)

array([[0.66993508, 0.24857968, 0.02470002, 0.47338155],
       [0.17824928, 0.13560145, 0.71791007, 0.62844866],
       [0.03625596, 0.057144  , 0.80698409, 0.5611129 ],
       [0.67486803, 0.04981967, 0.55898514, 0.9260684 ]])

In [49]:
np.random.randn(11, 4)

array([[[-2.85010381, -1.10506364, -0.32716569, ..., -1.20227339,
         -0.72041391,  0.28920973],
        [ 0.31353772,  0.52639193, -0.63601604, ..., -1.0343298 ,
         -1.92217491,  0.07287745],
        [ 0.12134494, -0.87247627, -0.91717806, ..., -1.26841255,
          0.13936803,  0.08564983],
        [-0.24354996, -0.42318584, -0.19251861, ..., -1.10127872,
         -0.66812845, -2.34310066]],

       [[ 1.48566636,  0.26966316, -1.4219189 , ..., -0.95746424,
          0.80197977, -1.19960898],
        [ 0.53351678,  1.70994033,  0.37109042, ...,  1.26605539,
          0.66024254, -0.78980023],
        [ 1.32605136, -0.07734613, -0.64205091, ..., -0.46678852,
         -2.21323382,  0.59926233],
        [-2.23314259,  0.52566715, -0.20228702, ...,  0.57220488,
          0.68094975, -0.10355134]],

       [[ 0.37332364,  1.32557927, -0.39471218, ...,  0.39973546,
         -0.04285423, -0.63491679],
        [-0.17933268,  0.66074707, -1.46748203, ..., -0.92344917,
          0.

In [54]:
np.random.randint(1,100,5)

array([29, 97, 64, 63, 12])

In [65]:
np.random.seed(552)
np.random.rand(4)

array([0.05934238, 0.38494112, 0.43062102, 0.80260343])

In [66]:
np.random.seed(552)
np.random.rand(4)

array([0.05934238, 0.38494112, 0.43062102, 0.80260343])

In [67]:
arr = np.arange(4)

In [70]:
ranarr = np.random.randint(0,50,10)

In [71]:
ranarr

array([34, 19, 19, 30, 46, 11,  0, 43, 46, 12])

In [72]:
arr.shape

(4,)

In [73]:
arr.reshape(2,2)

array([[0, 1],
       [2, 3]])

In [74]:
ranarr.max()

46

In [75]:
ranarr.min()

0

In [77]:
ranarr.argmin()

6

In [78]:
ranarr.argmin()

6

In [79]:
ranarr.dtype

dtype('int64')

In [80]:
arr = np.arange(0,11)
arr[3]

3

In [82]:
arr[2:4]

array([2, 3])